steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "Dockerfile",
        "-t",
        "northamerica-northeast1-docker.pkg.dev/hadji-ml-api/hadji-api/hadji:$TAG_NAME",
        "-t",
        "northamerica-northeast1-docker.pkg.dev/hadji-ml-api/hadji-api/hadji:latest",
        ".",
        "--cache-from",
        "northamerica-northeast1-docker.pkg.dev/hadji-ml-api/hadji-api/hadji:latest",
      ]
    # push the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "northamerica-northeast1-docker.pkg.dev/hadji-ml-api/hadji-api/hadji:latest",
      ]
    # deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "hadji-ml-api",
        "--image",
        "northamerica-northeast1-docker.pkg.dev/hadji-ml-api/hadji-api/hadji:$TAG_NAME",
        "--region",
        "northamerica-northeast1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port=8080",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
